const invoices = [
{
        status: true,
        invoiceNo: 123,
        from: "Shift",
        billTo: "Onedio",
        invoiceDate: "15/08/2022",
        dueDate: "15/09/2022",
        projectName: "Content Management Desktop Application ",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercise null pariatur. consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. ",
        unitPrice: "10.000",
        quantity: 1,
        extras: "3.000",
        subTotal: "13.000",
        taxRate: "10",
        totalPrice: "14.300",
        paymentType: "Credit Card",
    },
    {
        status: false,
        invoiceNo: 345,
        from: "Shift",
        billTo: "Onedio",
        invoiceDate: "15/08/2022",
        dueDate: "15/09/2022",
        projectName: "Invoice Desktop Application",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercise null pariatur. consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. ",
        unitPrice: "10.000",
        quantity: 1,
        extras: "3.000",
        subTotal: "13.000",
        taxRate: "10",
        totalPrice: "14.300",
        paymentType: "Credit Card",
    },
    {
        status: true,
        invoiceNo: 678,
        from: "Shift",
        billTo: "Onedio",
        invoiceDate: "15/08/2022",
        dueDate: "15/09/2022",
        projectName: "Android Application ",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercise null pariatur. consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. ",
        unitPrice: "10.000",
        quantity: 1,
        extras: "3.000",
        subTotal: "13.000",
        taxRate: "10",
        totalPrice: "14.300",
        paymentType: "Credit Card",
    },
    {
        status: false,
        invoiceNo: 890,
        from: "Shift",
        billTo: "Onedio",
        invoiceDate: "15/08/2022",
        dueDate: "15/09/2022",
        projectName: "Content Management Mobile Application",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercise null pariatur. consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. ",
        unitPrice: "10.000",
        quantity: 1,
        extras: "3.000",
        subTotal: "13.000",
        taxRate: "10",
        totalPrice: "14.300",
        paymentType: "Credit Card",
    }
];

export default invoices;